name: flutter_swiper_view
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.8
homepage: https://github.com/feicien/flutter_swiper_view

dependencies:
  flutter:
    sdk: flutter


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
